export const CITIES: Record<string, number> = {
  Baghdad: 0,
  Basra: 545,
  Karbala: 100,
  Najaf: 160,
  Diyala: 75,
  Babil: 95,
  Wasit: 180,
  Maysan: 365,
  "Dhi Qar": 375,
  Muthanna: 460,
  Qadisiyah: 195,
  Anbar: 110,
  Salahaddin: 175,
  Kirkuk: 250,
  Nineveh: 400,
  Erbil: 360,
  Sulaymaniyah: 340,
  Dohuk: 470,
  Standby: 0,
  Off: 0,
  "Over-night": 0,
  "Half-Day": 0,
};

export const CITY_NAMES = Object.keys(CITIES);

export const CITY_BADGE_COLORS: Record<string, string> = {
  Baghdad: "bg-yellow-100 text-yellow-800 border-yellow-300",
  Standby: "bg-amber-100 text-amber-800 border-amber-300",
  Off: "bg-gray-100 text-gray-600 border-gray-300",
  "Half-Day": "bg-green-100 text-green-800 border-green-300",
  "Over-night": "bg-blue-100 text-blue-800 border-blue-300",
};

export const DEFAULT_CITY_BADGE = "bg-yellow-100 text-yellow-800 border-yellow-300";

export const TEAMS = [
  "US", "KS", "AT", "N.A", "MR", "TH", "CT", "DX", "OR", "MI",
  "SP", "SY", "SRS", "Mech.", "All", "PET CT", "XP", "Medical Furniture",
  "HDR", "PACS", "Mech. CT", "Mech. MR", "Mech. TH", "Mech. MI", "SS",
];

export const ENGINEERS = [
  "Abbas Khaleel Safar Haidar",
  "Abdullah Ahmed Abbas",
  "Abdullah Faez",
  "Abdullah Mohsen",
  "Ahmed Abdul monem Ahmed",
  "Ahmed Alaa Mohammed",
  "Ahmed Ali",
  "Ahmed Bahjat",
  "Ahmed Fouad",
  "Ahmed Husain",
  "Ahmed Ibrahem Jallod",
  "Ahmed Sabah Hasan",
  "Ahmed Salman",
  "Ahmed Sami",
  "Ahmed Shihab Ahmed",
  "Akeel Sami Akeel",
  "Alaa Mohamed",
  "Ali Abdulhussein Hadi",
  "Ali Akram",
  "Ali Hoobi",
  "Ali Mohammed Ghazi",
  "Ali Najem",
  "Amer Ibrahim Abdulameer",
  "Amro Yasar",
  "Azel hameed",
  "Binay Shorsh Abdulla",
  "Dania Wadah Abdulhussain",
  "Dhurgham Faiz",
  "Duha Mustafa Kamil",
  "Fatin Ayssar Munir",
  "Fayad Mohammed Fayad",
  "Haider Fareed Abdul Qader",
  "Haider Hisham",
  "Humam reyad",
  "Hussein Majid Sarhan",
  "Ibrahim Ahmed Mohammed",
  "Imran Issa",
  "Jaafar Mohammed Hamid Anberr",
  "Jafeer Mohamed Saddam",
  "Kaywan Mohammed Saeed",
  "Khalid Abdulrazaq Abdulljabar",
  "Krikor Mugardich",
  "Laith Ali Hameed",
  "Layth faris",
  "Maher Mahmod",
  "Marwa Rasim Mohammed",
  "Maryam Abdulsalam",
  "Maytham Yassin",
  "Mohamad Saad",
  "Mohammad Noori Hamzah",
  "Mohammed Abdulkhaliq Fawzi",
  "Mohammed Hassan",
  "Mohammed Naser",
  "Mohammed Shamsaldeen",
  "Mohammed Thamer",
  "Mohammed Zaki",
  "Mohammed fadhil",
  "Mouamal Saaed",
  "Mudhar Mohammed Hussein",
  "Muntather Sabah",
  "Muqtada Khaled Abdulridha Abed",
  "Mustafa Adnan Abdulrahman",
  "Mustafa Amer Mohammed",
  "Mustafa Ayad",
  "Mustafa Mohammed Taha",
  "Mustafa Qussay Ismaeel",
  "Mustafa Sabah",
  "Nazar Mishal Shaban",
  "Noor Alhuda Mubder",
  "Oday Muwafaq Qasim",
  "Raghda Amer Abed",
  "Rehab Mahmoud Yousif Abdullah",
  "Saif mohammed",
  "Saify Ayad",
  "Sarah Mohammed Omar",
  "Sarya abdullmunem awad",
  "Shahad Mouayad",
  "Taha Yousef Jankeer",
  "Wissam Faeq Mohammed Ali",
  "Yahya Ahmed Rushdi",
  "Yasir abdulkraeem",
  "Yousif Hilal",
  "Zeyad Aed",
  "habeeb hakal habeeb",
  "karam hamid",
];

export const DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export const DAY_ABBRS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
